version: '2'
services:
    quoiquonmange-app:
        image: quoiquonmange
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://quoiquonmange-mysql:3306/quoiquonmange?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    quoiquonmange-mysql:
        extends:
            file: mysql.yml
            service: quoiquonmange-mysql
